name: life_line
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.14
  http: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.4
  sensors_plus: ^6.1.1
  geolocator: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_lints: ^5.0.0

# flutter splash / launch screen
flutter_native_splash:
  color: "#ffffff" 
  image: assets/splash.png
  android: true
  ios: true
  android_gravity: center

  android12:
    image: assets/splash.png
    icon_background_color: "#ffffff"
    image_dark: assets/splash.png
    icon_background_color_dark: "#000000"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/favicon.png" 

flutter:
  uses-material-design: true
